name: CD

on:
  push:
    branches: [main]
    paths:
      - "llm-evaluator-api-service/**"
      - ".github/workflows/cd.yml"
  workflow_dispatch:

jobs:
  service-cd:
    uses: ./llm-evaluator-api-service/.github/workflows/cd.yml
    secrets:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      INFERENCE_API_KEY: ${{ secrets.INFERENCE_API_KEY }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
      TF_STATE_REGION: ${{ secrets.TF_STATE_REGION }}
      SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
      SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
