name: CI

on:
  push:
    branches: [main]
    paths:
      - "llm-evaluator-api-service/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "llm-evaluator-api-service/**"
      - ".github/workflows/ci.yml"

jobs:
  service-ci:
    uses: ./llm-evaluator-api-service/.github/workflows/ci.yml
